export const products = [
  {
    id: 1,
    title: "Burger",
    description: "Burger With Cheese",
    price: "500",
    img: "https://img.buzzfeed.com/buzzfeed-static/static/2020-04/23/18/enhanced/228cf987b68c/enhanced-83-1587667052-8.jpg",
    quantity: 1,
  },
  {
    id: 2,
    title: "Momos",
    description: " Spicy ",
    price: "300",
    img: "https://www.skymetweather.com/themes/skymet/images/gallery/toplists/20-Must-Try-Food-Items-in-Delhi/3.jpg",
    quantity: 1,
  },
  {
    id: 3,
    title: "Samosa",
    description: "With Green And Red Chatni",
    price: "100",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK9IhH_yzBbMSlEk43Vh-Ms-3nP7yUuPRaSA&usqp=CAU",
    quantity: 1,
  },
  {
    id: 4,
    title: "Boiled Egg",
    description: "With Sauce",
    price: "200",
    img: "https://miro.medium.com/max/1250/0*aEOPyvz7YK__lroz",
    quantity: 1,
  },
  {
    id: 5,
    title: "Fruit Shake",
    description: "With Milk And Cream",
    price: "500",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVmh8jThZEW3wmQ7qDVmojTSYRoUYj2cMCVwZRnIUCjcRQJJmjbLU07HbgBHcwDWv_3tM&usqp=CAU",
    quantity: 1,
  },
  {
    id: 6,
    title: "Pani Puri",
    description: "With Spicy ingredient",
    price: "3500",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhGjSSFAEFeckZ_hNSvp2Oe3UDYxzORdctEOuSJeXZZBSt_BWGzzuMRx1qONAwZT4iDzM&usqp=CAU",
    quantity: 1,
  },
  {
    id: 7,
    title: "Laddu",
    description: "Pure Ghee",
    price: "2500",
    img: "https://i.pinimg.com/originals/e7/cf/30/e7cf3058a52dfe5100a28b6225a808c1.png",
    quantity: 1,
  },
  {
    id: 8,
    title: "IDLI",
    description: "With Sambhar",
    price: "500",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Idli_Sambar.JPG/640px-Idli_Sambar.JPG",
    quantity: 1,
  },
];
